// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfwkhmkhnsblhyjafmel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5md2tobWtobnNibGh5amFmbWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMzM2ODMsImV4cCI6MjA1MzgwOTY4M30.SF39NoPmNQHUt5aervCK_clnB1MFm7kSTLzqBNHc-FU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);